# 项目级 Gradle 设置。
# IDE（例如 Android Studio）用户请注意：
# 通过 IDE 配置的 Gradle 设置 *会覆盖* 本文件中的设置。
# 关于如何配置构建环境的更多细节，参见
# http://www.gradle.org/docs/current/userguide/build_environment.html
# 指定 Gradle 守护进程使用的 JVM 参数。
# 该设置特别适合用来调整内存相关参数。
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# 启用后，Gradle 会以试验性的并行模式运行。
# 该选项只应配合解耦的多模块工程使用。更多细节参见
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
# 启用后，配置缓存允许 Gradle 在构建配置（例如构建脚本）没有发生任何变化时，
# 完全跳过配置阶段；此外 Gradle 还会对任务执行施加性能优化。
org.gradle.configuration-cache=true